dataset_path: garden
downsample_factor: 4
output_dir: splat_output
print_interval: 500
initial_opacity: 0.2
initial_scale_num_neighbors: 3
initial_scale_factor: 0.8
max_initial_scale: 0.1
near_thresh: 0.3
mh_dist: 3.0
cull_mask_padding: 100
num_iters: 30000
ssim_frac: 0.2
base_lr: 1e-3
xyz_lr_multiplier_init: 2e-1
xyz_lr_multiplier_final: 2e-3
quat_lr_multiplier: 4.0
scale_lr_multiplier: 10.0
opacity_lr_multiplier: 50
rgb_lr_multiplier: 5.0
sh_lr_multiplier: 0.25
test_eval_interval: 500
test_split_ratio: 9
use_background: true
use_background_end: 10000
reset_opacity_interval: 3000
reset_opacity_value: 0.01
reset_opacity_start: 1050
reset_opacity_end: 15000
use_sh_precompute: true
max_sh_band: 3
add_sh_band_interval: 1000
use_split: true
use_clone: true
use_delete: true
adaptive_control_start: 500
adaptive_control_end: 20000
adaptive_control_interval: 100
max_gaussians: 4250000
delete_opacity_threshold: 0.005
uv_grad_threshold: 2e-4
split_scale_factor: 1.6
max_anisotropy: 50.0
